### ISSUE TITLE
Divergent solution and model sequences

### ISSUE THREAD

**Issue by everyday847** [mmagnus/RNA-Puzzles-Standardized-Submissions#3]
In at least puzzles 03 and 05, the sequences for the solution and models are different. I assume the sequence provided as part of the puzzle is the same as the model sequence, and the sequence of the structure that was ultimately determined may differ. Is that generally the case? How was this accounted for in heavyatom RMSD calculations?

**Comment by mmagnus** [comment]
@chichaumiau can you answer this question :-)

**Comment by chichaumiau** [comment]
Hi Andrew, Yes, you find the case. The can be common, because our crystallographer friends may have a couple of crystals before solving the structure, or have many clones with slightly variations in sequence. And they may give RNA-Puzzles a different sequence, because the structure finally solved is slightly different. RNA-Puzzles is grateful to the crystallographer and cannot restrict too much. 
When the sequences are different, we can only take the common structure parts. For example, when there are two mutations in the same chain, the parts to be compared are only the 3 fragments of the same sequence. 
This kind of case happens quite rare in recent puzzles.

**Comment by mmagnus** [comment]
@chichaumiau thanks!

I added more information about these mismatches to the readmes. 

This is for example rmsd calculation by me (independent from the RNA Puzzle offical results):

```
$ rna_calc_rmsd.py -t 3_solution_0_rpr.pdb --target_selection A:1-47+49+51+53-84 --model_selection A:1-47+49+51+53-84 *.pdb
rmsd_calc_rmsd_to_target
--------------------------------------------------------------------------------
method: all-atom-built-in
# of models: 13
3_bujnicki_1_rpr.pdb 12.16 1747
3_bujnicki_2_rpr.pdb 14.25 1747
```
